import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Left from '../components/Left'
import Middle from '../components/Middle'
import Right from '../components/Right'

export default function Home() {
	return (
		<div className=''>
			<Head>
				<title>Rup-dash</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{/* Header Part Starts */}
			<div className='w-full  bg-blue-700 text-white text-center p-2'>
				Lorem Ipsum is simply dummy text of the printing
			</div>
			{/* Header Part Ends */}

			{/* Body Part Starts */}
			<div className='grid grid-cols-10   bg-black text-white md:h-full  	'>
				{/* Left */}
				<div className=' col-span-2 m-5'>
					<Left />
				</div>

				{/* Middle */}
				<div className='col-span-5  border-l-2 border-gray-700 bor'>
					<Middle />
				</div>

				{/* Right */}
				<div className=' col-span-3   border-l-2 border-gray-700 '>
					<Right />
				</div>
			</div>
		</div>
	)
}
